// Code generated by mockery v2.10.4. DO NOT EDIT.

package storagemocks

import (
	context "context"

	mygame "github.com/rfdez/my-game-backend/internal"
	mock "github.com/stretchr/testify/mock"
)

// AnswerRepository is an autogenerated mock type for the AnswerRepository type
type AnswerRepository struct {
	mock.Mock
}

// FindByEventIDAndQuestionID provides a mock function with given fields: _a0, _a1, _a2
func (_m *AnswerRepository) FindByEventIDAndQuestionID(_a0 context.Context, _a1 mygame.EventID, _a2 mygame.QuestionID) (mygame.Answer, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 mygame.Answer
	if rf, ok := ret.Get(0).(func(context.Context, mygame.EventID, mygame.QuestionID) mygame.Answer); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(mygame.Answer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, mygame.EventID, mygame.QuestionID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
