// Code generated by mockery v2.10.4. DO NOT EDIT.

package storagemocks

import (
	context "context"

	mygame "github.com/rfdez/my-game-backend/internal"
	mock "github.com/stretchr/testify/mock"
)

// QuestionRepository is an autogenerated mock type for the QuestionRepository type
type QuestionRepository struct {
	mock.Mock
}

// Find provides a mock function with given fields: _a0, _a1
func (_m *QuestionRepository) Find(_a0 context.Context, _a1 mygame.QuestionID) (mygame.Question, error) {
	ret := _m.Called(_a0, _a1)

	var r0 mygame.Question
	if rf, ok := ret.Get(0).(func(context.Context, mygame.QuestionID) mygame.Question); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(mygame.Question)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, mygame.QuestionID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
